version: "2"

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    command: --appendonly yes --requirepass "123456"

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017

#  crawler2:
#    image: inner.registry:5000/spider
#    networks:
#      - spider
#    deploy:
#      mode: replicated
#      replicas: 3
#      restart_policy:
#        condition: on-failure
#      endpoint_mode: dnsrr
#      placement:
#        constraints:
#          - "node.labels.spider-role == crawler2"

volumes:
  redis_data:
  mongo_data:
